FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

# Install toolchain and required build tools
RUN apt-get update && apt-get install -y \
    build-essential \
    mingw-w64 \
    autoconf \
    automake \
    libtool \
    pkg-config \
    wget \
    git \
    python3 \
    cmake \
    ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV CC=x86_64-w64-mingw32-gcc
ENV CXX=x86_64-w64-mingw32-g++
ENV PREFIX=/sdl2-windows

# --- Build libogg ---
WORKDIR /build
RUN wget https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.gz && \
    tar -xf libogg-1.3.5.tar.gz && rm libogg-1.3.5.tar.gz
WORKDIR /build/libogg-1.3.5
RUN ./configure --host=x86_64-w64-mingw32 --prefix=/sdl2-windows --disable-shared --enable-static && \
    make -j$(nproc) && make install

# --- Build libvorbis ---
WORKDIR /build
RUN wget https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.gz && \
    tar -xf libvorbis-1.3.7.tar.gz && rm libvorbis-1.3.7.tar.gz
WORKDIR /build/libvorbis-1.3.7
RUN ./configure --host=x86_64-w64-mingw32 --prefix=/sdl2-windows --with-ogg=/sdl2-windows --disable-shared --enable-static && \
    make -j$(nproc) && make install

# --- Build SDL2 ---
WORKDIR /build
RUN wget https://github.com/libsdl-org/SDL/releases/download/release-2.30.3/SDL2-2.30.3.tar.gz && \
    tar -xf SDL2-2.30.3.tar.gz && rm SDL2-2.30.3.tar.gz
WORKDIR /build/SDL2-2.30.3
RUN ./configure --host=x86_64-w64-mingw32 --prefix=/sdl2-windows --disable-shared --enable-static && \
    make -j$(nproc) && make install

# --- Build full libxmp from GitHub (static) ---
WORKDIR /build
RUN rm -rf libxmp &&  \
    git clone https://github.com/libxmp/libxmp.git && \
    rm -f /sdl2-windows/libxmp.* && \
    cd libxmp && \
    make distclean || true && \
    ./autogen.sh && \
    ./configure --host=x86_64-w64-mingw32 --prefix=/sdl2-windows --disable-shared --enable-static && \
    make -j$(nproc) && make install

# --- libmodplug (CMake build) ---
RUN git clone https://github.com/Konstanty/libmodplug.git && \
    cd libmodplug && mkdir build && cd build && \
    cmake .. -G "Unix Makefiles" \
      -DCMAKE_SYSTEM_NAME=Windows \
      -DCMAKE_C_COMPILER=${CC} \
      -DCMAKE_CXX_COMPILER=${CXX} \
      -DCMAKE_INSTALL_PREFIX=${PREFIX} \
      -DBUILD_SHARED_LIBS=OFF && \
    make -j$(nproc) && make install

# --- Build SDL2_mixer with static linking and minimal formats ---
WORKDIR /build
RUN rm -rf SDL2_mixer-2.8.0 && \
    rm -rf /sdl2-windows/lib/libSDL2_mixer.* && \
    wget https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.8.0/SDL2_mixer-2.8.0.tar.gz && \
    tar -xf SDL2_mixer-2.8.0.tar.gz && rm SDL2_mixer-2.8.0.tar.gz && \
    cd SDL2_mixer-2.8.0 && \
  ./configure \
    --host=x86_64-w64-mingw32 \
    --prefix=/sdl2-windows \
    --with-sdl-prefix=/sdl2-windows \
    --disable-shared --enable-static \
    --disable-music-mp3 \
    --disable-music-mp3-mpg123 \
    --disable-music-flac \
    --disable-music-opus \
    --disable-music-wavpack \
    --enable-music-ogg \
    --enable-music-mod-xmp \
    --enable-music-mod \
    --enable-music-mod-modplug \
    --enable-music-midi \
    LIBS="-L/sdl2-windows/lib -lxmp -lmodplug -logg -lvorbis -lvorbisfile" && \
    make clean && \
    make -j$(nproc) && make install

    # https://github.com/libsdl-org/SDL_mixer/blob/release-2.8.x/configure

# --- Build zlib (static) ---
WORKDIR /build
RUN wget https://cfrankb.com/files/libs/zlib-1.3.1.tar.gz && \
    tar -xf zlib-1.3.1.tar.gz && rm zlib-1.3.1.tar.gz
WORKDIR /build/zlib-1.3.1
RUN CROSS_PREFIX=x86_64-w64-mingw32- ./configure --static --prefix=/sdl2-windows && \
    make -j$(nproc) && make install


# clean up
RUN rm -rf /build

# --- Final container setup ---
WORKDIR /workspace
CMD ["/bin/bash"]
