FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    g++ \
    git \
    wget \
    curl \
    autoconf \
    automake \
    libtool \
    pkg-config \
    gettext \
    libasound2-dev \
    libpulse-dev \
    libx11-dev \
    libxext-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    && rm -rf /var/lib/apt/lists/*

# ---------- Build SDL2 ----------
RUN git clone https://github.com/libsdl-org/SDL.git && \
    cd SDL && \
    git checkout release-2.32.6 && \
    ./autogen.sh && \
    ./configure --prefix=/usr/local \
                --disable-shared \
                --enable-static \
                --with-pic \
                CXX=g++ \
                CFLAGS="-O2" && \
    make -j$(nproc) && make install

# ---------- Build libxmp ----------
RUN git clone https://github.com/libxmp/libxmp.git && \
    cd libxmp && \
    ./autogen.sh && \
    ./configure --prefix=/usr/local \
                --disable-shared \
                --enable-static \
                --with-zlib \
                CXX=g++ \
                CFLAGS="-O2" && \
    make -j$(nproc) && make install

# ---------- Build SDL2_mixer ----------
RUN git clone https://github.com/libsdl-org/SDL_mixer.git && \
    cd SDL_mixer && \
    git checkout release-2.8.1 && \
    ./autogen.sh && \
    ./configure --prefix=/usr/local \
                --disable-shared \
                --enable-static \
                --enable-music-ogg \
                --enable-music-mod \
                --enable-music-mod-xmp \
                --disable-music-mod-modplug \
                --disable-music-mp3 \
                --disable-music-flac \
                --disable-music-opus \
                --disable-music-wavpack \
                --disable-music-midi-native \
                --disable-music-midi-fluidsynth \
                CXX=g++ \
                CFLAGS="-O2" && \
    make -j$(nproc) && make install

# ---------- Build zlib (static) ----------
    RUN wget https://zlib.net/zlib-1.3.1.tar.gz && \
    tar -xf zlib-1.3.1.tar.gz && \
    cd zlib-1.3.1 && \
    ./configure --static --prefix=/usr/local && \
    make -j$(nproc) && make install

# ---------- Build libogg (static) ----------
RUN wget https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.gz && \
    tar -xf libogg-1.3.5.tar.gz && \
    cd libogg-1.3.5 && \
    ./configure --disable-shared --enable-static --prefix=/usr/local && \
    make -j$(nproc) && make install


# Cleanup source dirs 
RUN rm -rf SDL SDL_mixer libxmp zlib-1.3.1* libogg-1.3.5*

CMD ["/bin/bash"]
