# Override Clang-on-MSVC link rules
set(CMAKE_C_CLANG_CREATE_SHARED_LIBRARY
    "<CMAKE_C_COMPILER> <FLAGS> <CMAKE_SHARED_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)
set(CMAKE_CXX_CLANG_CREATE_SHARED_LIBRARY
    "<CMAKE_CXX_COMPILER> <FLAGS> <CMAKE_SHARED_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)

set(CMAKE_C_CLANG_LINK_EXECUTABLE
    "<CMAKE_C_COMPILER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)
set(CMAKE_CXX_CLANG_LINK_EXECUTABLE
    "<CMAKE_CXX_COMPILER> <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)
