/*
    cs3-runtime-sdl
    Copyright (C) 2025 Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
//////////////////////////////////////////////////
// autogenerated

#pragma once

enum Bricks
{
    BRICKS_BRICK40            = 0x00,
    BRICKS_BRICK39            = 0x01,
    BRICKS_BRICK04            = 0x02,
    BRICKS_BRICK08            = 0x03,
    BRICKS_BRICK09            = 0x04,
    BRICKS_BRICK29            = 0x05,
    BRICKS_BRICK30            = 0x06,
    BRICKS_BRICK13            = 0x07,
    BRICKS_BRICK23            = 0x08,
    BRICKS_BRICK15            = 0x09,
    BRICKS_BRICK16            = 0x0a,
    BRICKS_BRICK17            = 0x0b,
    BRICKS_BRICK18            = 0x0c,
    BRICKS_BRICK19            = 0x0d,
    BRICKS_BRICK20            = 0x0e,
    BRICKS_BRICK28            = 0x0f,
    BRICKS_BRICK40_LEN        = 0x01,
    BRICKS_BRICK39_LEN        = 0x01,
    BRICKS_BRICK04_LEN        = 0x01,
    BRICKS_BRICK08_LEN        = 0x01,
    BRICKS_BRICK09_LEN        = 0x01,
    BRICKS_BRICK29_LEN        = 0x01,
    BRICKS_BRICK30_LEN        = 0x01,
    BRICKS_BRICK13_LEN        = 0x01,
    BRICKS_BRICK23_LEN        = 0x01,
    BRICKS_BRICK15_LEN        = 0x01,
    BRICKS_BRICK16_LEN        = 0x01,
    BRICKS_BRICK17_LEN        = 0x01,
    BRICKS_BRICK18_LEN        = 0x01,
    BRICKS_BRICK19_LEN        = 0x01,
    BRICKS_BRICK20_LEN        = 0x01,
    BRICKS_BRICK28_LEN        = 0x01,
    BRICKS_TOTAL_COUNT        = 0x10,
};
