/*
    cs3-runtime-sdl
    Copyright (C) 2025 Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
//////////////////////////////////////////////////
// autogenerated

#pragma once

#define BRICKS_BRICK40_LEN        0x01
#define BRICKS_BRICK39_LEN        0x01
#define BRICKS_BRICK04_LEN        0x01
#define BRICKS_BRICK08_LEN        0x01
#define BRICKS_BRICK09_LEN        0x01
#define BRICKS_BRICK29_LEN        0x01
#define BRICKS_BRICK30_LEN        0x01
#define BRICKS_BRICK13_LEN        0x01
#define BRICKS_BRICK23_LEN        0x01
#define BRICKS_BRICK15_LEN        0x01
#define BRICKS_BRICK16_LEN        0x01
#define BRICKS_BRICK17_LEN        0x01
#define BRICKS_BRICK18_LEN        0x01
#define BRICKS_BRICK19_LEN        0x01
#define BRICKS_BRICK20_LEN        0x01
#define BRICKS_BRICK28_LEN        0x01

#define BRICKS_BRICK40            0x00
#define BRICKS_BRICK39            0x01
#define BRICKS_BRICK04            0x02
#define BRICKS_BRICK08            0x03
#define BRICKS_BRICK09            0x04
#define BRICKS_BRICK29            0x05
#define BRICKS_BRICK30            0x06
#define BRICKS_BRICK13            0x07
#define BRICKS_BRICK23            0x08
#define BRICKS_BRICK15            0x09
#define BRICKS_BRICK16            0x0a
#define BRICKS_BRICK17            0x0b
#define BRICKS_BRICK18            0x0c
#define BRICKS_BRICK19            0x0d
#define BRICKS_BRICK20            0x0e
#define BRICKS_BRICK28            0x0f
#define BRICKS_TOTAL_COUNT        0x10
