/*
    cs3-runtime-sdl
    Copyright (C) 2024  Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
//////////////////////////////////////////////////
// autogenerated

#ifndef _ANNIE__HDR_H
#define _ANNIE__HDR_H

#define ANNIE_ANNIE2         0x00
#define ANNIE_ANNIE2_2       0x01
#define ANNIE_ANNIE2_3       0x02
#define ANNIE_ANNIE2_4       0x03
#define ANNIE_ANNIE2_5       0x04
#define ANNIE_ANNIE2_6       0x05
#define ANNIE_ANNIE2_7       0x06
#define ANNIE_ANNIE2_8       0x07
#define ANNIE_ANNIE2_9       0x08
#define ANNIE_ANNIE2_A       0x09
#define ANNIE_ANNIE2_B       0x0a
#define ANNIE_ANNIE2_C       0x0b
#define ANNIE_ANNIE2_D       0x0c
#define ANNIE_ANNIE2_E       0x0d
#define ANNIE_ANNIE2_F       0x0e
#define ANNIE_ANNIE2_10      0x0f
#define ANNIE_ANNIE2_11      0x10
#define ANNIE_ANNIE2_12      0x11
#define ANNIE_ANNIE2_13      0x12
#define ANNIE_ANNIE2_14      0x13

#endif
