/*
    cs3-runtime-sdl
    Copyright (C) 2025  Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

//////////////////////////////////////////////////
// autogenerated

#include <cstddef>
#include "bossdata.h"

constexpr int DEMON_MOVING_BASE = 0;
constexpr int DEMON_MOVING_LEN = 4;
constexpr int DEMON_ATTACK_BASE = 4;
constexpr int DEMON_ATTACK_LEN = 8;
constexpr int DEMON_HURT_BASE = 12;
constexpr int DEMON_HURT_LEN = 4;
constexpr int DEMON_DEATH_BASE = 16;
constexpr int DEMON_DEATH_LEN = 6;

bossData_t g_bosses[] = {
    {
        .name = "Mr. Demon",
        .speed = 2,
        .hp = 64,
        .type = 0xb0,
        .score = 1000,
        .damage = 16,
        .flags = 0,
        .moving = {DEMON_MOVING_BASE, DEMON_MOVING_LEN},
        .attack = {DEMON_ATTACK_BASE, DEMON_ATTACK_LEN},
        .hurt = {DEMON_HURT_BASE, DEMON_HURT_LEN},
        .death = {DEMON_DEATH_BASE, DEMON_DEATH_LEN},
        .hitbox = {2, 6, 4, 2},
        .sheet = 0,
    },
};

bossData_t *getBossData(const int type)
{
    constexpr size_t bossCount = sizeof(g_bosses) / sizeof(g_bosses[0]);
    for (size_t i = 0; i < bossCount; ++i)
    {
        if (g_bosses[i].type == type)
            return &g_bosses[i];
    }
    return nullptr;
}
