/*
    cs3-runtime-sdl
    Copyright (C) 2025  Francois Blanchette

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

//////////////////////////////////////////////////
// autogenerated

#pragma once

#include <cstdint>
#include "rect.h"

#define FLAG_FIREBALL 0x1

#define BOSS_MR_DEMON 0xb0


struct boss_seq_t
{
    int base;
    int lenght;
};

struct bossData_t
{
    const char* name;
    int speed;
    int hp;
    int type;
    int score;
    int damage;
    uint32_t flags;
    boss_seq_t moving;
    boss_seq_t attack;
    boss_seq_t hurt;
    boss_seq_t death;
    Rect hitbox;
    int sheet;
};

bossData_t *getBossData(const int type);
