// autogenerated

#include <cstdint>
#pragma once
const uint8_t * getCustomChars();

#define CHARS_CUSTOM           0x80
#define CHARS_CUR_UP           0x80
#define CHARS_CUR_DOWN         0x81
#define CHARS_CUR_LEFT         0x82
#define CHARS_CUR_RIGHT        0x83
#define CHARS_TUP              0x84
#define CHARS_TDOWN            0x85
#define CHARS_TLEFT            0x86
#define CHARS_TRIGHT           0x87
#define CHARS_DIAMOND          0x88
#define CHARS_STAR             0x89
#define CHARS_CARET            0x8a
#define CHARS_BUTTERFLY        0x8b
#define CHARS_CRUNCH           0x8c
#define CHARS_CHEST            0x8d
#define CHARS_PLAYER           0x8e
#define CHARS_LADDER           0x8f
#define CHARS_SMILEY           0x90
#define CHARS_BRICK            0x91
#define CHARS_WALL             0x92
#define CHARS_CRUSHER          0x93
