//////////////////////////////////////////////////
// autogenerated

#define SOUND_NONE                 0x00
#define SOUND_GRUUP                0x01
#define SOUND_KEY                  0x02
#define SOUND_0009                 0x03
#define SOUND_COIN1                0x04
