name: Build Steam Linux Version

on:
  push:
    branches: [master, gpu]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    # Run all steps inside the Sniper SDK container
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive # Important if you bake in SDL/zlib

      - name: Checkout Data Repo
        uses: actions/checkout@v6
        with:
          repository: cfrankb/cs3-data-private
          path: data
          token: ${{ secrets.CS3_REPO_TOKEN }} # Only if internal access is enabled

      - name: Checkout Steamworks SDK
        uses: actions/checkout@v6
        with:
          repository: cfrankb/steamwork-sdk-private
          path: external/steamworks
          token: ${{ secrets.CS3_REPO_TOKEN }} # Only if internal access is enabled

      #- name: Configure CMake
      #  run: |
      #    cmake -B build \
      #      -DCMAKE_BUILD_TYPE=Release \
      #      -DBUILDING_FOR_STEAM=ON

      - name: Build
        #run: cmake --build build --config Release
        run: |
          pwd
          ls -l
          ls -s external
          python3 bin/refresh.py
          chmod +x bin/build.sh
          bin/build.sh steam_linux

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Use @v4 for standard stability
        with:
          name: steam-linux-build
          path: |
            build/steam-linux/cs3-runtime
            external/steamworks/sdk/redistributable_bin/linux64/libsteam_api.so
            packages/steam/steam_appid.txt
            data
          retention-days: 7
